### ISSUE TITLE
Fix 3:00 timer

### ISSUE THREAD

**Issue by Samwalton9** [Samwalton9/CustomsBot#10]
"3:00" is hardcoded as the starting string timer, even though I changed the timer to 2 minutes, so the timer starts at 3:00 and immediately changes to 1:59.

**Comment by Appenzaller** [comment]
Hardcoded squad and region votes to "2:00" in the upcoming PR. Left the password command untouched, does anything need to be done about that one at all?

**Comment by Samwalton9** [comment]
Nope, that timer was correct.
